chore(CI): try to deploy on my vm

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -23,8 +23,8 @@ jobs:
     - name: Debug Connectivity
       run: |
         echo "Testing connectivity..."
-        ping -c 4 <server-ip> || echo "Ping failed"
-        nc -zv <server-ip> 22 || echo "Port 22 unreachable"
+        ping -c 4 ${{secrets.SSH_HOST}} || echo "Ping failed"
+        nc -zv ${{secrets.SSH_HOST}} 22 || echo "Port 22 unreachable"
 
     - name: Copy Project to Server
       run: |
